In [1]:
import numpy as np
import matplotlib
from matplotlib import colormaps
import matplotlib.pyplot as plt
import healpy as hp
import itertools

In [2]:
# Set random star positions in spherical coordinates
np.random.seed(9)
num_stars = 4
npair = num_stars*(num_stars-1)/2
theta = np.random.uniform(0, np.pi,num_stars)  # colatitude E[0, pi]
phi = np.random.uniform(0, 2*np.pi, num_stars) # longitude [0, 2pi]

In [3]:
# unit vector in R3, given two angles, \theta E[0,pi] and \phi E[0,2pi]
def skyvec(theta,phi): 
    st = np.sin(theta)
    cp = np.cos(phi)
    sp = np.sin(phi)
    ct = np.cos(theta)
    return np.array([st*cp,st*sp,ct])

In [4]:
n1=skyvec(theta,phi)
n2=skyvec(theta,phi)
#print(np.dot(n1,n2))
n1n2=np.outer(n1,n2)
print(len(np.outer(n1,n2)))
#print(n1n2)
n1n2.shape

12


(12, 12)

In [24]:
a=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
b=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
#b=[[7,8],[9,10],[11,12]]

#dot =np.dot(a,b)
out = np.outer(a,b)

for_dot=[]
for_outer=[]
for i in range(4):
    for j in range(4):
        fdot = np.dot(a[i],b[j])
        fouter = np.outer(a[i],b[j])
        for_dot.append(fdot)
        for_outer.append(fouter)
            
inter_dot = []
inter_outer = []
for pair in itertools.combinations(np.arange(4),2):
    idx_p,idx_q = pair
    A=a[idx_p]
    B=b[idx_q]
    dot_int = np.dot(A,B)
    outer_int = np.outer(np.array(a).flatten(), np.array(b).flatten())[idx_p,idx_q] 
    inter_dot.append(dot_int)
    inter_outer.append(outer_int)
    #inter_dot+=dot_int

#print('Dot fuction from numpy:', dot)
print('Dot (for):', for_dot)
print('Dot (intertools):', inter_dot)
print('Outer (numpy):', out) 
print('Outer (for):', for_outer)
print('Outer (intertools):', inter_outer)
print(out.shape)

Dot (for): [14, 32, 50, 68, 32, 77, 122, 167, 50, 122, 194, 266, 68, 167, 266, 365]
Dot (intertools): [32, 50, 68, 122, 167, 266]
Outer (numpy): [[  1   2   3   4   5   6   7   8   9  10  11  12]
 [  2   4   6   8  10  12  14  16  18  20  22  24]
 [  3   6   9  12  15  18  21  24  27  30  33  36]
 [  4   8  12  16  20  24  28  32  36  40  44  48]
 [  5  10  15  20  25  30  35  40  45  50  55  60]
 [  6  12  18  24  30  36  42  48  54  60  66  72]
 [  7  14  21  28  35  42  49  56  63  70  77  84]
 [  8  16  24  32  40  48  56  64  72  80  88  96]
 [  9  18  27  36  45  54  63  72  81  90  99 108]
 [ 10  20  30  40  50  60  70  80  90 100 110 120]
 [ 11  22  33  44  55  66  77  88  99 110 121 132]
 [ 12  24  36  48  60  72  84  96 108 120 132 144]]
Outer (for): [array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]]), array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]]), array([[ 7,  8,  9],
       [14, 16, 18],
       [21, 24, 27]]), array([[10, 11, 12],
       [20, 22, 24],


In [ ]:
np.random.seed(7)
ns = 3
phi_test = np.random.uniform(0,2*np.pi,ns)
theta_test = np.arccos(np.random.uniform(-1,1,ns))
p_t=skyvec(theta_test,phi_test)
q_t=skyvec(theta_test,phi_test)
pq=np.dot(p_t,q_t)

results_dot=[]
results_outer=[]
for pair in itertools.combinations(np.arange(ns),2):
    idx_p,idx_q = pair
    p=skyvec(theta_test[idx_p],phi_test[idx_p])
    q=skyvec(theta_test[idx_q],phi_test[idx_q])
    dot = np.dot(p,q)
    outer = np.outer(p[idx_p],q[idx_q])
    results_dot.append(dot)
    results_outer.append(outer)

print('p',p)
print('q',q)
print('pq shape',pq.shape)
print('pdotq',pq)
print('pq dot (intertools)',results_dot)
print('pq outer (intertools)',results_outer)
print('pq outer shape',len(results_outer))

In [ ]:
np.outer([1,2],[5,6])

In [ ]:
test1=np.outer(a[0],b[0])
test1.shape

In [ ]:
nside = 32
npix = hp.nside2npix(nside)
vtheta, vphi = hp.pix2ang(nside, np.arange(npix))
vdir = skyvec(vtheta,vphi)
v= np.column_stack(vdir)
np.array(v)
np.array(v).shape

vdir.shape

In [ ]:
np.arange(3)

In [6]:
import healpy as hp
import numpy as np

nside = 128
npix = hp.nside2npix(nside)
theta, phi = hp.pix2ang(nside, np.arange(npix))

def skyvec(theta,phi): #unit vector
    ct = np.cos(theta)
    st = np.sin(theta)
    cp = np.cos(phi)
    sp = np.sin(phi)
    return np.array([st*cp,st*sp,ct])
    
dir = skyvec(theta,phi)
print(np.shape(dir))

print(npix)

(3, 196608)
196608


In [95]:
A=hp.pix2ang(12,np.arange(4))

In [41]:
nside = 32
npix = hp.nside2npix(nside)
print(npix)

12288


In [99]:
theta0 = np.deg2rad(48) 
phi0 = np.deg2rad(264)
v = skyvec(theta0,phi0).reshape(3,1)
v

array([[-0.07767979],
       [-0.7390738 ],
       [ 0.66913061]])